### ISSUE TITLE
Change amounts' unit of getmwbalance from litoshi to  LTC

### ISSUE THREAD

**Issue by mosadialiou** [ltc-mweb/libmw#22]
Actually `./litecoin-cli -testnet getmwebbalance` returns the output below
```
{
  "confirmed": 0,
  "unconfirmed": 1500000000,
  "locked": 0,
  "immature": 0
}
```

where `1500000000` is in `litoshi`. 
For consistency reasons with other old RPC calls like `getbalance`, it's good to set them in LTC instead

**Comment by DavidBurkett** [comment]
Fixed: https://github.com/ltc-mweb/litecoin/pull/5/commits/72a54f6b0b8d99259dd863d384c8f3320f0b3f7b
